Revert "Revert "[aptitude @ emove the pkgAcqFileSane class, whose enhancements are superseded by the changes in pkgAcqFile, and update references to it. (Closes: #299127)]""
The upstream change seems reasonable and makes code simpler (and less
dependent on the details of pkgAcquire::Item interface needed to know
in order to inherit from it). Why was it reverted in ALT? Let's see
whether it works: the only place this stuff is used is for "aptitude
download" (cmdline_download.cc).

Ok, I see, the problem is with the DestFile parameter absent in APT in
pkgAcqFile and pkgAcqArchive classes, unfortunately:

pkg_acqfile.cc:113:20: error: no matching function for call to 'pkgAcqFile::pkgAcqFile(pkgAcquire*&, std::string, const string&, const long long unsigned int&, std::string, const char*, const char [1], std::string&)'
  113 |        "", DestFile);
      |                    ^
In file included from pkg_acqfile.h:20,
                 from pkg_acqfile.cc:23:
/usr/include/apt-pkg/acquire-item.h:257:4: note: candidate: 'pkgAcqFile::pkgAcqFile(pkgAcquire*, const string&, const string&, long unsigned int, const string&, const string&)'
  257 |    pkgAcqFile(pkgAcquire *Owner,const string &URI, const string &MD5,unsigned long Size,
      |    ^~~~~~~~~~
/usr/include/apt-pkg/acquire-item.h:257:4: note:   candidate expects 6 arguments, 8 provided

This reverts commit 2c7726c5af1312afa1477cdbca3cfa3278e19ea4.